## Numpy Array & Basics
learn about numpy 

In [2]:
import numpy as np

### Creating Array form list ...

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1d array : ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array : ", arr_2d)

1d array :  [1 2 3 4 5]
2d array :  [[1 2 3]
 [4 5 6]]


## List vs Numpy Array

In [ ]:
py_list = [1,2,3]
print("list multiply : ", py_list * 2)  # double the list

np_list = np.array([1,2,3])
print("np array multiply : ", np_list * 2)   # multiple each ele seprately, required high cpu & gpu usage

list multiply :  [1, 2, 3, 1, 2, 3]
np array multiply :  [2 4 6]


## Time Complexity

In [21]:
import time
start = time.time()

py_list  = [i*2 for i in range(1, 10000000)]
print("List Multiply : ", time.time() - start)

start = time.time()
np_list = np.arange(1, 10000000) * 2
print("Nump Multiply : ", time.time() - start)

List Multiply :  7.80555534362793
Nump Multiply :  0.0822899341583252


## Creating Matrices

In [30]:
# zero matrices

zeros = np.zeros((3,3))
print("zeros : \n", zeros)


# ones array

ones = np.ones((3,3))
print("ones : \n", ones)


constants = np.full((2,2), 3)
print("constants : \n", constants)

random = np.random.random((3,3))
print("random : \n", random)

sequence = np.arange(0, 10)
print("sequence : \n", sequence)



zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
constants : 
 [[3 3]
 [3 3]]
random : 
 [[0.45683576 0.4840519  0.52159344]
 [0.436433   0.8542296  0.16385542]
 [0.97119838 0.42586904 0.89373632]]
sequence : 
 [0 1 2 3 4 5 6 7 8 9]


### Vector, Matrices and Tensors

In [32]:
scaller = 4;     # just a single value is scaller, also 0-d tensor
print("scaller : ", scaller)

vector = np.array([1,2,3])  # 1-d also a tensor
print("vector : ", vector)

matrice = np.array([[1,2,3],[4,5,6],[7,8,9]])   # 2-d also a 2d tensor
print("matrice : \n", matrice)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) * 2 # n-d matrix is tensor
print("tensor : \n", tensor) 

scaller :  4
vector :  [1 2 3]
matrice : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor : 
 [[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


### Properties of Matrix

In [34]:
arr = np.array([[1,2,3], [4,5,6]])

print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("Data Type : ", arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
Data Type :  int64


### Array reshaping

In [46]:
arr = np.arange(9)
print("Original Array : ", arr)

new = arr.reshape(3,3)
print("Reshaped Array : \n", new)

# return copy
flat = arr.flatten()
print("Flatten array : \n", flat)

# change in original array
ravel = arr.ravel()
print("Ravel : ", ravel)

transpose = new.T
print("Transpose : \n", transpose)



Original Array :  [0 1 2 3 4 5 6 7 8]
Reshaped Array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Flatten array : 
 [0 1 2 3 4 5 6 7 8]
Ravel :  [0 1 2 3 4 5 6 7 8]
Transpose : 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
