## NUMPY array operations

In [2]:
import numpy as np

In [5]:
# although in python we do have various inbuild operations for array, but in np we hae several more which makes life easy pizzy !

np_arr = np.array([[1,2,3], [4,5,6]])

print("Print 1st element of 1st row : ", np_arr[1,1])
print("Entire row : ", np_arr[1])
print("Entire col : ", np_arr[:, 1])

Print 1st element of 1st row :  5
Entire row :  [4 5 6]
Entire col :  [2 5]


### SORTING

In [9]:
np_arr1d = np.array([3,1,3,5,6])
print("Sorted Array : ", np.sort(np_arr1d))

np_arr2d = np.array([[7,3,1], [5,2,9]])
print("Sorted 2d array row wise: \n", np.sort(np_arr2d, axis=1))

np_arr2d = np.array([[7,3,1], [5,2,9]])
print("Sorted 2d array col wise: \n", np.sort(np_arr2d, axis=0))

Sorted Array :  [1 3 3 5 6]
Sorted 2d array row wise: 
 [[1 3 7]
 [2 5 9]]
Sorted 2d array col wise: 
 [[5 2 1]
 [7 3 9]]


## Filters

In [3]:
nums = np.array([1,2,3,4,5,6,7,8,9,10])

print("filtered data : ", nums[nums % 2 == 0])

filtered data :  [ 2  4  6  8 10]


Filtering by mask

In [ ]:
mask = nums > 5
print("filtered data : ", nums[mask])

indexing = [1, 2, 3]
print("index values ", nums[indexing])

np_where = np.where(nums > 5)
print(np_where)
print("where filter : ", nums[np_where])
# output - 
# (array([ 6,  7,  8,  9, 10]),)

# creating array with complete where condition, 
np_cond = np.where(nums > 5, nums * 2, nums)
print("condition : ", np_cond)
# output - 
# [ 2  4  6  8 10 12 14 16 18 20]

filtered data :  [ 6  7  8  9 10]
index values  [2 3 4]
(array([5, 6, 7, 8, 9]),)
where filter :  [ 6  7  8  9 10]
condition :  [ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# adding
arr3 = np.concat([arr1, arr2])

print(arr3)

# array compatability
print("array compatability : ", arr1.shape == arr2.shape, arr1.shape)


# adding new row in a matrix
new_row = np.array([7,8,9])

arr4 = np.vstack([[7], [8]]) # add row in array
arr5 = np.hstack([[7], [8]]) # add col new array 

print(arr4)
print(arr5)

#removing

arr = np.array([1,2,3,4,5])
print("removed element : ", np.delete(arr, 2))




[1 2 3 4 5 6]
array compatability :  True (3,)
[[7]
 [8]]
[7 8]
removed element :  [1 2 4 5]
